# Generated by Django 3.2 on 2022-10-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Marki',
                'verbose_name_plural': 'Marka',
            },
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Rodzaje sprzętu',
                'verbose_name_plural': 'Rodzaj sprzętu',
            },
        ),
        migrations.CreateModel(
            name='HardwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('description', models.TextField(max_length=255, verbose_name='Opis')),
                ('state', models.IntegerField(choices=[(0, 'Nowy'), (1, 'Używany'), (2, 'Uszkodzony')], default=0, verbose_name='Stan techniczny')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwarebrand', verbose_name='Marka')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaretype', verbose_name='Rodzaj')),
            ],
            options={
                'verbose_name': 'Modele',
                'verbose_name_plural': 'Model',
            },
        ),
    ]
