# Generated by Django 3.2 on 2022-10-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwaremodel',
            name='imei1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IMEI1'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='imei2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IMEI2'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='op_system',
            field=models.IntegerField(choices=[(0, 'Brak'), (1, 'Android'), (2, 'iOS'), (3, 'Windows'), (4, 'Niestandardowy')], default=0, verbose_name='System operacyjny'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='ram',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Pamięć RAM'),
        ),
        migrations.AddField(
            model_name='hardwaremodel',
            name='storage',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Pamięć wbudowana'),
        ),
    ]
