# Generated by Django 3.2 on 2022-10-24 18:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nazwisko')),
                ('mail', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numer telefonu')),
                ('note', models.TextField(max_length=255, verbose_name='Uwagi')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_status', models.IntegerField(choices=[(0, 'Nowy'), (1, 'W trakcie'), (2, 'Błąd'), (3, 'Naprawiony')], default=0, verbose_name='Status naprawy')),
                ('description', models.TextField(max_length=255, verbose_name='Opis')),
                ('note', models.TextField(max_length=255, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.FloatField(default=0.0, verbose_name='Szacunkowy koszt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Klient')),
                ('hardware_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaremodel', verbose_name='Model')),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaretype', verbose_name='Rodzaj sprzętu')),
            ],
            options={
                'verbose_name': 'Naprawa',
                'verbose_name_plural': 'Naprawy',
            },
        ),
    ]
