# Generated by Django 3.2 on 2022-10-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hardware', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('type', models.CharField(max_length=50, verbose_name='Rodzaj')),
                ('signature', models.CharField(max_length=50, verbose_name='Oznaczenie')),
                ('description', models.TextField(max_length=255, verbose_name='Opis')),
                ('stock', models.IntegerField(choices=[(0, 'Nie'), (1, 'Tak')], default=1, verbose_name='Na stanie')),
                ('hardware_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaremodel', verbose_name='Model')),
                ('hardware_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hardware.hardwaretype', verbose_name='Rodzaj')),
            ],
            options={
                'verbose_name': 'Części',
                'verbose_name_plural': 'Części',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=20, verbose_name='Nr dokumentu')),
                ('cost', models.FloatField(default=0.0, verbose_name='Kwota')),
                ('sold_at', models.DateField(verbose_name='Data sprzedaży')),
                ('due_at', models.DateField(verbose_name='Termin zapłaty')),
                ('nip', models.CharField(max_length=10, verbose_name='NIP')),
                ('city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('post_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('payment_type', models.IntegerField(choices=[(0, 'Gotówka'), (1, 'Przelew')], default=0, verbose_name='Forma płatności')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Nabywca')),
            ],
            options={
                'verbose_name': 'Faktury',
                'verbose_name_plural': 'Faktura',
            },
        ),
    ]
